[package]
name = "bevy_spatial"
description = "A crate for tracking bevy entities in spatial indices."
documentation = "https://docs.rs/bevy_spatial"
version = "0.1.1"
license = "MIT OR Apache-2.0"
edition = "2021"
keywords = ["gamedev", "bevy", "spatial", "kdtree", "rtree"]
repository = "https://github.com/laundmo/bevy-spatial"
readme = "README.md"
authors = ["Laurin Schmidt"]

[dependencies]
bevy = { version = "0.8.0", default-features = false}
num-traits = { version = "0.2.15" }
bevy_prototype_debug_lines = { version = "0.8", optional = true }
# R*-Tree dependencies
rstar = { version = "0.9.3", optional = true }
# KD-Tree dependencies
kd-tree = { version = "0.4.1", optional = true }
typenum = { version = "1.15.0", optional = true }

[features]
debug = ["dep:bevy_prototype_debug_lines"]
rstar = ["dep:rstar"]
kdtree = ["dep:kd-tree"]

[dev-dependencies]
bevy = { version = "0.8.0", features = ["dynamic"] }
criterion = { version = "0.3", features = ["html_reports"] }
kiddo = "0.2.4"
kd-tree = "0.4.1"
kdtree = "0.6.0"
rand = "0.8.5"
quadtree_rs = "0.1.2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[[bench]]
name = "kdtrees"
path = "benches/kdtrees.rs"
harness = false


[[bench]]
name = "quadtree"
path = "benches/quadtree.rs"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
